/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginOperadorRouteImport } from './routes/login-operador'
import { Route as LoginClienteRouteImport } from './routes/login-cliente'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIndexRouteImport } from './routes/operador.index'
import { Route as OperadorGaleriaRouteImport } from './routes/operador.galeria'

const LoginOperadorRoute = LoginOperadorRouteImport.update({
  id: '/login-operador',
  path: '/login-operador',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/login-cliente',
  path: '/login-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIndexRoute = OperadorIndexRouteImport.update({
  id: '/operador/',
  path: '/operador/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorGaleriaRoute = OperadorGaleriaRouteImport.update({
  id: '/operador/galeria',
  path: '/operador/galeria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-operador': typeof LoginOperadorRoute
  '/operador/galeria': typeof OperadorGaleriaRoute
  '/operador/': typeof OperadorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-operador': typeof LoginOperadorRoute
  '/operador/galeria': typeof OperadorGaleriaRoute
  '/operador': typeof OperadorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-operador': typeof LoginOperadorRoute
  '/operador/galeria': typeof OperadorGaleriaRoute
  '/operador/': typeof OperadorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login-cliente'
    | '/login-operador'
    | '/operador/galeria'
    | '/operador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-cliente'
    | '/login-operador'
    | '/operador/galeria'
    | '/operador'
  id:
    | '__root__'
    | '/'
    | '/login-cliente'
    | '/login-operador'
    | '/operador/galeria'
    | '/operador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginClienteRoute: typeof LoginClienteRoute
  LoginOperadorRoute: typeof LoginOperadorRoute
  OperadorGaleriaRoute: typeof OperadorGaleriaRoute
  OperadorIndexRoute: typeof OperadorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-operador': {
      id: '/login-operador'
      path: '/login-operador'
      fullPath: '/login-operador'
      preLoaderRoute: typeof LoginOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-cliente': {
      id: '/login-cliente'
      path: '/login-cliente'
      fullPath: '/login-cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/': {
      id: '/operador/'
      path: '/operador'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/galeria': {
      id: '/operador/galeria'
      path: '/operador/galeria'
      fullPath: '/operador/galeria'
      preLoaderRoute: typeof OperadorGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginClienteRoute: LoginClienteRoute,
  LoginOperadorRoute: LoginOperadorRoute,
  OperadorGaleriaRoute: OperadorGaleriaRoute,
  OperadorIndexRoute: OperadorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
