/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginOperadorRouteImport } from './routes/login-operador'
import { Route as LoginClienteRouteImport } from './routes/login-cliente'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OperadorIndexRouteImport } from './routes/operador.index'
import { Route as ClienteIndexRouteImport } from './routes/cliente.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OperadorVendasRouteImport } from './routes/operador.vendas'
import { Route as OperadorUsuariosRouteImport } from './routes/operador.usuarios'
import { Route as OperadorUploadRouteImport } from './routes/operador.upload'
import { Route as OperadorGaleriaRouteImport } from './routes/operador.galeria'
import { Route as OperadorConfiguracoesRouteImport } from './routes/operador.configuracoes'
import { Route as AdminEmpresasRouteImport } from './routes/admin.empresas'
import { Route as ApiPublicHooksCleanupPhotosRouteImport } from './routes/api.public.hooks.cleanup-photos'

const LoginOperadorRoute = LoginOperadorRouteImport.update({
  id: '/login-operador',
  path: '/login-operador',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginClienteRoute = LoginClienteRouteImport.update({
  id: '/login-cliente',
  path: '/login-cliente',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorIndexRoute = OperadorIndexRouteImport.update({
  id: '/operador/',
  path: '/operador/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteIndexRoute = ClienteIndexRouteImport.update({
  id: '/cliente/',
  path: '/cliente/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OperadorVendasRoute = OperadorVendasRouteImport.update({
  id: '/operador/vendas',
  path: '/operador/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorUsuariosRoute = OperadorUsuariosRouteImport.update({
  id: '/operador/usuarios',
  path: '/operador/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorUploadRoute = OperadorUploadRouteImport.update({
  id: '/operador/upload',
  path: '/operador/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorGaleriaRoute = OperadorGaleriaRouteImport.update({
  id: '/operador/galeria',
  path: '/operador/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const OperadorConfiguracoesRoute = OperadorConfiguracoesRouteImport.update({
  id: '/operador/configuracoes',
  path: '/operador/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmpresasRoute = AdminEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicHooksCleanupPhotosRoute =
  ApiPublicHooksCleanupPhotosRouteImport.update({
    id: '/api/public/hooks/cleanup-photos',
    path: '/api/public/hooks/cleanup-photos',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login-cliente': typeof LoginClienteRoute
  '/login-operador': typeof LoginOperadorRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/operador/configuracoes': typeof OperadorConfiguracoesRoute
  '/operador/galeria': typeof OperadorGaleriaRoute
  '/operador/upload': typeof OperadorUploadRoute
  '/operador/usuarios': typeof OperadorUsuariosRoute
  '/operador/vendas': typeof OperadorVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/operador/': typeof OperadorIndexRoute
  '/api/public/hooks/cleanup-photos': typeof ApiPublicHooksCleanupPhotosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login-cliente': typeof LoginClienteRoute
  '/login-operador': typeof LoginOperadorRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/operador/configuracoes': typeof OperadorConfiguracoesRoute
  '/operador/galeria': typeof OperadorGaleriaRoute
  '/operador/upload': typeof OperadorUploadRoute
  '/operador/usuarios': typeof OperadorUsuariosRoute
  '/operador/vendas': typeof OperadorVendasRoute
  '/admin': typeof AdminIndexRoute
  '/cliente': typeof ClienteIndexRoute
  '/operador': typeof OperadorIndexRoute
  '/api/public/hooks/cleanup-photos': typeof ApiPublicHooksCleanupPhotosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login-cliente': typeof LoginClienteRoute
  '/login-operador': typeof LoginOperadorRoute
  '/admin/empresas': typeof AdminEmpresasRoute
  '/operador/configuracoes': typeof OperadorConfiguracoesRoute
  '/operador/galeria': typeof OperadorGaleriaRoute
  '/operador/upload': typeof OperadorUploadRoute
  '/operador/usuarios': typeof OperadorUsuariosRoute
  '/operador/vendas': typeof OperadorVendasRoute
  '/admin/': typeof AdminIndexRoute
  '/cliente/': typeof ClienteIndexRoute
  '/operador/': typeof OperadorIndexRoute
  '/api/public/hooks/cleanup-photos': typeof ApiPublicHooksCleanupPhotosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login-cliente'
    | '/login-operador'
    | '/admin/empresas'
    | '/operador/configuracoes'
    | '/operador/galeria'
    | '/operador/upload'
    | '/operador/usuarios'
    | '/operador/vendas'
    | '/admin/'
    | '/cliente/'
    | '/operador/'
    | '/api/public/hooks/cleanup-photos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login-cliente'
    | '/login-operador'
    | '/admin/empresas'
    | '/operador/configuracoes'
    | '/operador/galeria'
    | '/operador/upload'
    | '/operador/usuarios'
    | '/operador/vendas'
    | '/admin'
    | '/cliente'
    | '/operador'
    | '/api/public/hooks/cleanup-photos'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login-cliente'
    | '/login-operador'
    | '/admin/empresas'
    | '/operador/configuracoes'
    | '/operador/galeria'
    | '/operador/upload'
    | '/operador/usuarios'
    | '/operador/vendas'
    | '/admin/'
    | '/cliente/'
    | '/operador/'
    | '/api/public/hooks/cleanup-photos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginClienteRoute: typeof LoginClienteRoute
  LoginOperadorRoute: typeof LoginOperadorRoute
  OperadorConfiguracoesRoute: typeof OperadorConfiguracoesRoute
  OperadorGaleriaRoute: typeof OperadorGaleriaRoute
  OperadorUploadRoute: typeof OperadorUploadRoute
  OperadorUsuariosRoute: typeof OperadorUsuariosRoute
  OperadorVendasRoute: typeof OperadorVendasRoute
  ClienteIndexRoute: typeof ClienteIndexRoute
  OperadorIndexRoute: typeof OperadorIndexRoute
  ApiPublicHooksCleanupPhotosRoute: typeof ApiPublicHooksCleanupPhotosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login-operador': {
      id: '/login-operador'
      path: '/login-operador'
      fullPath: '/login-operador'
      preLoaderRoute: typeof LoginOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-cliente': {
      id: '/login-cliente'
      path: '/login-cliente'
      fullPath: '/login-cliente'
      preLoaderRoute: typeof LoginClienteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/': {
      id: '/operador/'
      path: '/operador'
      fullPath: '/operador/'
      preLoaderRoute: typeof OperadorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/': {
      id: '/cliente/'
      path: '/cliente'
      fullPath: '/cliente/'
      preLoaderRoute: typeof ClienteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/operador/vendas': {
      id: '/operador/vendas'
      path: '/operador/vendas'
      fullPath: '/operador/vendas'
      preLoaderRoute: typeof OperadorVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/usuarios': {
      id: '/operador/usuarios'
      path: '/operador/usuarios'
      fullPath: '/operador/usuarios'
      preLoaderRoute: typeof OperadorUsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/upload': {
      id: '/operador/upload'
      path: '/operador/upload'
      fullPath: '/operador/upload'
      preLoaderRoute: typeof OperadorUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/galeria': {
      id: '/operador/galeria'
      path: '/operador/galeria'
      fullPath: '/operador/galeria'
      preLoaderRoute: typeof OperadorGaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operador/configuracoes': {
      id: '/operador/configuracoes'
      path: '/operador/configuracoes'
      fullPath: '/operador/configuracoes'
      preLoaderRoute: typeof OperadorConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/empresas': {
      id: '/admin/empresas'
      path: '/empresas'
      fullPath: '/admin/empresas'
      preLoaderRoute: typeof AdminEmpresasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/hooks/cleanup-photos': {
      id: '/api/public/hooks/cleanup-photos'
      path: '/api/public/hooks/cleanup-photos'
      fullPath: '/api/public/hooks/cleanup-photos'
      preLoaderRoute: typeof ApiPublicHooksCleanupPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminEmpresasRoute: typeof AdminEmpresasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmpresasRoute: AdminEmpresasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginClienteRoute: LoginClienteRoute,
  LoginOperadorRoute: LoginOperadorRoute,
  OperadorConfiguracoesRoute: OperadorConfiguracoesRoute,
  OperadorGaleriaRoute: OperadorGaleriaRoute,
  OperadorUploadRoute: OperadorUploadRoute,
  OperadorUsuariosRoute: OperadorUsuariosRoute,
  OperadorVendasRoute: OperadorVendasRoute,
  ClienteIndexRoute: ClienteIndexRoute,
  OperadorIndexRoute: OperadorIndexRoute,
  ApiPublicHooksCleanupPhotosRoute: ApiPublicHooksCleanupPhotosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
